# Generated by Django 4.2.10 on 2024-03-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=8, verbose_name='Номер заказа')),
                ('tg_user_id', models.BigIntegerField(verbose_name='ID пользователя в Telegram')),
                ('processed', models.BooleanField(verbose_name='Обработано')),
                ('failed', models.BooleanField(verbose_name='Завершено с ошибкой')),
            ],
            options={
                'verbose_name': 'Уведомление о заказе',
                'verbose_name_plural': 'Уведомления о заказах',
            },
        ),
    ]
