# Generated by Django 4.2.10 on 2024-03-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernotification',
            name='failed',
        ),
        migrations.AddField(
            model_name='ordernotification',
            name='failed_attempts_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Число неудачных попыток'),
        ),
    ]
